config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'
  get 'sign-out', to: 'authentication#destroy'
  resources :courses do
    resources :lessons
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    
    if session[:user_id].present?
      User.find(session[:user_id])
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @courses = Course.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= link_to "Sign Out", sign_out_path %>
<% else %>
  <%= link_to "Sign In", sign_in_path %>
  <%= link_to "Sign Up", sign_up_path %>
<% end %>
 
<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<% if current_user %>
  <%= current_user.email %>
<hr>

<%= link_to "Add a course", new_course_path %>

<br>

<% @courses.each do |course| %>
<p> Name: <%= course.name %></p>
<p> Capacity: <%= course.capacity %></p>
<br>
<% end %>

<% else %>
<hr>
Please sign in or sign up!
<% end %>